version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
    command: npm run dev